### ISSUE TITLE
ip4_input Error Condition

### ISSUE THREAD

**Issue by WenyuanShao** [WenyuanShao/eos#3]
ip4_input might have error conditions [here](https://github.com/WenyuanShao/eos/blob/087d8853f2a4e4b677b9ae697aa8333610376394/src/components/implementation/no_interface/SSL_nf/eos_SSL_nf.c#L302). And p should be freed if ip4_input returns an error

**Comment by ryuxin** [comment]
This is wired. lwip says it always return ERR_OK https://github.com/WenyuanShao/eos/blob/fwp/src/components/lib/lwip/lwip-2.1.2/src/core/ipv4/ip4.c#L422-L423
make sure doing the error checking correctly
