### ISSUE TITLE
The memory used by lwip

### ISSUE THREAD

**Issue by WenyuanShao** [WenyuanShao/eos#4]
Lwip takes a lot more memory than we expected which makes each SSL or echo server fwp much larger than we want.

**Comment by ryuxin** [comment]
this looks like eat lots of memory (MEMP_NUM_TCP_SEG)
https://github.com/WenyuanShao/eos/blob/fwp/src/components/lib/lwip/cos/include/lwipopts.h#L44

**Comment by ryuxin** [comment]
fixed
